feat: v1
asynq-io/fastapi-views pull request #19
Opened 2024-10-06 19:14 UTC by RaRhAeu

2024-10-28 13:12 UTC, GithubMateusz commented on examples/app.py
> +
Not used

2024-10-28 13:51 UTC, GithubMateusz requested changes

2024-10-28 13:51 UTC, GithubMateusz commented on fastapi_views/pagination.py
> +    items: list[T] = Field([], description="Array of objects returned")
Czy tutaj nie jest bardziej valid użycie default_factory?

2024-10-28 13:51 UTC, GithubMateusz commented on fastapi_views/types.py
> +    async def list(self, *args: Any, **kwargs: Any) -> list[Entity]: ...
To nie jest już używane

2024-10-28 13:51 UTC, GithubMateusz commented on fastapi_views/views/mixins.py
>  R = TypeVar("R", bound=Union[AsyncRepository, Repository])
To można usunąć również

2024-10-28 15:03 UTC, RaRhAeu commented on fastapi_views/pagination.py
> +    items: list[T] = Field([], description="Array of objects returned")
Nie ma znaczenia bo pydantic pod spodem robi deepcopy mutowalnych defaultów.

2024-10-29 06:12 UTC, GithubMateusz approved these changes

2024-11-17 18:20 UTC, merged